-- Profile scoring table for Applyze
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE UNIQUE,

  -- Academic data
  gpa DECIMAL(3,2),
  sat_score INTEGER,
  act_score INTEGER,
  ap_courses JSONB DEFAULT '[]'::jsonb, -- [{name: string, score: number}]
  coursework_rigor TEXT, -- 'low', 'medium', 'high', 'very_high'
  class_rank INTEGER,
  class_size INTEGER,

  -- Extracurriculars
  activities JSONB DEFAULT '[]'::jsonb, -- [{name, role, hours_per_week, years, description}]
  awards JSONB DEFAULT '[]'::jsonb, -- [{name, level, year, description}]
  leadership_positions JSONB DEFAULT '[]'::jsonb,

  -- Personal context
  intended_major TEXT,
  first_generation BOOLEAN DEFAULT FALSE,
  urm_status TEXT, -- 'yes', 'no', 'prefer_not_to_say'
  location TEXT,
  financial_aid_needed BOOLEAN DEFAULT FALSE,

  -- Essays & recommendations (future)
  essay_topics JSONB DEFAULT '[]'::jsonb,
  recommenders_count INTEGER DEFAULT 0,

  -- AI-generated scores (0-100)
  overall_score INTEGER,
  academic_score INTEGER,
  extracurricular_score INTEGER,
  essay_score INTEGER,
  recommendation_score INTEGER,

  -- AI analysis
  strengths TEXT[], -- ['Strong GPA', 'Leadership in robotics club']
  weaknesses TEXT[], -- ['Low test scores', 'Limited awards']
  improvement_suggestions JSONB DEFAULT '[]'::jsonb, -- [{action, priority, timeline}]

  -- College list (generated by AI)
  reach_schools JSONB DEFAULT '[]'::jsonb, -- [{name, chance_percentage}]
  target_schools JSONB DEFAULT '[]'::jsonb,
  safety_schools JSONB DEFAULT '[]'::jsonb,

  -- Meta
  completed_onboarding BOOLEAN DEFAULT FALSE,
  last_assessed_at TIMESTAMP WITH TIME ZONE,
  assessment_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast user lookups
CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON profiles(user_id);

-- Index for filtering by score
CREATE INDEX IF NOT EXISTS idx_profiles_overall_score ON profiles(overall_score);

-- Roadmap tasks table
CREATE TABLE IF NOT EXISTS roadmap_tasks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,

  title TEXT NOT NULL,
  description TEXT,
  category TEXT, -- 'academic', 'extracurricular', 'testing', 'essay', 'recommendation'
  priority TEXT, -- 'critical', 'high', 'medium', 'low'
  deadline DATE,
  estimated_impact INTEGER, -- score improvement points (+5, +10, etc.)

  completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMP WITH TIME ZONE,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_roadmap_tasks_profile_id ON roadmap_tasks(profile_id);
CREATE INDEX IF NOT EXISTS idx_roadmap_tasks_completed ON roadmap_tasks(completed, deadline);

-- Assessment history (for tracking progress over time)
CREATE TABLE IF NOT EXISTS assessment_history (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,

  overall_score INTEGER,
  academic_score INTEGER,
  extracurricular_score INTEGER,

  snapshot JSONB, -- full profile snapshot at this time

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_assessment_history_profile_id ON assessment_history(profile_id, created_at DESC);

-- Function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for profiles table
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Trigger for roadmap_tasks table
CREATE TRIGGER update_roadmap_tasks_updated_at BEFORE UPDATE ON roadmap_tasks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
